export enum Action {
  CREATE_NEWSLETTER = 'CREATE_NEWSLETTER',
  EDIT_NEWSLETTER = 'EDIT_NEWSLETTER',
  SUBMIT_FOR_REVIEW = 'SUBMIT_FOR_REVIEW',

  // Functional Admin
  APPROVE_NEWSLETTER = 'APPROVE_NEWSLETTER',
  REQUEST_CHANGES = 'REQUEST_CHANGES',
  COMMENT_NEWSLETTER = 'COMMENT_NEWSLETTER',
  VIEW_TRAZABILITY = 'VIEW_TRAZABILITY',
  REVIEW_CHANGES = 'REVIEW_CHANGES',

  // Super Admin
  MANAGE_TEMPLATES = 'MANAGE_TEMPLATES',
  MANAGE_USERS = 'MANAGE_USERS',
  CONFIGURE_AI_PARAMS = 'CONFIGURE_AI_PARAMS',

  // General usage
  USE_TEMPLATE = 'USE_TEMPLATE',
  GENERATE_AI_CONTENT = 'GENERATE_AI_CONTENT',
}
